### ISSUE TITLE
VERSION is 1.5.1 on master although 1.5.2 is already released

### ISSUE THREAD

**Issue by sonots** [resque/redis-namespace#121]
https://github.com/resque/redis-namespace/blob/7253bca2a5afb84e3294cde47fd4591d4463aa50/lib/redis/namespace/version.rb points 1.5.1 although redis-namespace 1.5.2 is already released https://rubygems.org/search?utf8=%E2%9C%93&query=redis-namespace

**Comment by johnpaulashenfelter** [comment]
1.6.0 is out now -- seems like this can be closed?

**Comment by sonots** [comment]
Thanks
