### ISSUE TITLE
Test with redis-rb 4.0.0 RC1

### ISSUE THREAD

**Issue by djanowski** [resque/redis-namespace#124]
I just released redis-rb 4.0.0 RC1.

Can you please test against it and report back?

Thank you!

**Comment by djanowski** [comment]
FYI redis-rb 4.0 is out.

**Comment by stepheneb** [comment]
Am also interested in using this with redis 4.0. Anything I can do to help?

**Comment by jeremy** [comment]
Supported with #136, released in 1.6.0
