### ISSUE TITLE
New gem version

### ISSUE THREAD

**Issue by bodrovis** [resque/redis-namespace#139]
Colleagues, could you please release a new version containing these changes https://github.com/resque/redis-namespace/commit/9cb81bfb3d76f26e63475beac2d23ce1ba7b896f so that issues similar to this one https://github.com/mperham/sidekiq/issues/3595 can be resolved? Thank you in advance!

**Comment by prettycoder** [comment]
@fw42 
Hi Florian, is this something you could do for us? Anything I can help with?

**Comment by hkdsun** [comment]
I believe we need one of our rubygems owners to do that (https://rubygems.org/gems/redis-namespace)

@hone @yaauie would one of you folks have some free cycles to take care of the release? Thanks!

**Comment by jesperronn** [comment]
Also, the following are owners according to rubygems and should be able to make a release:

* @steveklabnik 
* @defunkt 
* @chrisccerami 


If any of you could create the new release, it would be perfect!

**Comment by steveklabnik** [comment]
I can do that soon.

**Comment by steveklabnik** [comment]
```
Pushed redis-namespace 1.6.0 to rubygems.org.
```

**Comment by jesperronn** [comment]
Thanks! 👍
