### ISSUE TITLE
Passing 'lock' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0

### ISSUE THREAD

**Issue by everaldo** [resque/redis-namespace#143]
Hi!

Could you help me with that?

I'm using redis-lock

https://github.com/mlanett/redis-lock

**Comment by rwojnarowski** [comment]
From sidekiq's author:
https://github.com/mperham/sidekiq/issues/3716
```
I recommend removing redis-namespace.
http://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/
```

**Comment by rafaelfranca** [comment]
The redis-lock gem needs to be changed to stop calling the method lock in the namespace instance and instead call in the redis instance
