### ISSUE TITLE
Correct way to instantiate Redis object?

### ISSUE THREAD

**Issue by ryancmoon** [resque/redis-namespace#146]
The client is throwing this warning message:

> The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.

namespace.rb calls this warning without a way to fix it: 
Line 255

```
    def client
      warn("The client method is deprecated as of redis-rb 4.0.0, please use the new _client" +
            "method instead. Support for the old method will be removed in redis-namespace 2.0.") if @has_new_client_method
      _client
    end

    def _client
      @has_new_client_method ? @redis._client : @redis.client # for redis-4.0.0
```

All of these fail:
```
    redis = Redis.new(:url => url_goes_here)._client     # still using .new 
    redis = Redis._client    # does not exist  
```

**Comment by jeremy** [comment]
These are methods on Redis::Namespace objects, not Redis itself.
