### ISSUE TITLE
Support for UNLINK command

### ISSUE THREAD

**Issue by akshayrao14** [resque/redis-namespace#148]
Hello,

I was wondering if the [UNLINK command](https://redis.io/commands/unlink) is supported? When I tried to use it, I get an `undefined method 'unlink' for #<Redis::Namespace:0x00000006c1fb00>` error.

Thanks!
Akshay

**Comment by jeremy** [comment]
It is not yet supported. Check out how commands are explicitly declared here: https://github.com/resque/redis-namespace/blob/master/lib/redis/namespace.rb

Pull request welcome to add support + tests for this and other commands!

**Comment by akshayrao14** [comment]
@jeremy I've created pull request #150 for this issue. Please take a look whenever possible. Thanks.
