### ISSUE TITLE
I have a bug with mset command

### ISSUE THREAD

**Issue by buzjuka** [resque/redis-namespace#154]
redis-namespace - 1.6.0
redis - 4.0.1
redis-server - 3.0.6

```
z=Redis::Namespace.new(:test, redis: $redis)
=> <Redis::Namespace v1.6.0 with client v4.0.1 for redis://localhost:6379/0/test>

z.mset([:a, 1])
 => "OK"

z.get :a
 => "test:1"
```

mset add namespace prefix to each value.

I don't know maybe it's related to redis-server version or something like this

**Comment by rafaelfranca** [comment]
That make sense. Can you open a PR?
