### ISSUE TITLE
Ruby 2.7 Deprecations And Argument Forwarding

### ISSUE THREAD

**Issue by ytaben** [resque/redis-namespace#181]
As of ruby 2.7, converting last argument of a function to kwargs is deprecated (but kwargs are converted to a hash). This results in a deprecation warning (which becomes in an error in ruby 3.0) due to the following interaction:

In `redis` gem `lib/redis.rb:836`:
`def set(key, value, ex: nil, px: nil, nx: nil, xx: nil, keepttl: nil)`

In `resque` gem (which uses `redis-namespace`) `lib/resque/datastore:278`:
`@redis.set(redis_key_for_worker_pruning, worker.to_s, :ex => expiry, :nx => true)`

In `redis-namespace` `lib/redis/namespace:365`:
`def call_with_namespace(command, *args, &block)` (note: no `**kwargs`)
Later on line `442` we do `result = @redis.send(command, *args, &block)` 

This results in `warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

While I'm happy to whip up a fix and open a PR, I wanted to hear your thoughts (especially that you've allowed ruby 3.0 in gemspec) and confirm that this is not a misuse of the gem on client side (which does not seem to be the case because both Redis and the client code use kwargs which get converted to a hash by redis-namespace).
I didn't want to blindly add **kwargs to both lines 365 and 442 because there appears to be some logic in this function that _relies_ on this conversion of kwargs to hash.

Let me know if this is a valid problem and if you'd like me to dive deeper and fix it or if you want to take it from here. Thanks!

**Comment by byroot** [comment]
> (note: no **kwargs)

The gem uses the `ruby2_keywords` macro. We're running this gem on ruby 3 without any issue whatsoever.

It's up to you to update the code on your side to be compatible.

**Comment by ytaben** [comment]
@byroot I think the confusion came from the fact that github lists 1.6.0 as `latest` version but there is actually a newer version available on rubygems.
Thanks for the clarification.
