### ISSUE TITLE
Deprecation warning: Redis.current is deprecated and will be removed in 5.0

### ISSUE THREAD

**Issue by pedrofurtado** [resque/redis-namespace#189]
Hello! 👋 

Using the latest version of gem redis and redis-namespace, appears a deprecation warning like this below:

```
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /opt/rubies/3.0/lib/ruby/gems/3.0.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:245:in `initialize')
```

https://github.com/resque/redis-namespace/blob/v1.8.1/lib/redis/namespace.rb#L245

https://github.com/redis/redis-rb/blob/v4.6.0/lib/redis.rb#L39-L48

https://github.com/redis/redis-rb/issues/1064

**Comment by byroot** [comment]
```ruby
@redis = options[:redis] || Redis.current
```

So it's mostly the caller's responsability to pass a `Redis` instance here.
