### ISSUE TITLE
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0

### ISSUE THREAD

**Issue by djberg96** [resque/redis-namespace#234]
* Ruby 3.x on Linux
* redis-namespace 1.11.0 (via dependency)
* redis 4.6
* sidekiq 6.5.x
* All nestled in a Rails 6.1 app
* Cannot upgrade redis or sidekiq at the moment

I'm seeing the following warning message from redis-namespace:
```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end
```

I can replicate it like so:

```ruby
class SidekiqMiddleware::Stuff
  def call(_worker, job, _queue)
    send_to_morgue(job)
  end

  def send_to_morgue(msg)
    Sidekiq.logger.info { "Adding dead #{msg['class']} job #{msg['jid']}" }
    payload = Sidekiq.dump_json(msg)
    now = Time.now.to_f
    Sidekiq.redis do |conn|
      conn.multi do
        conn.zadd('dead', now, payload)
        conn.zremrangebyscore('dead', '-inf', now - Sidekiq::DeadSet.timeout)
        conn.zremrangebyrank('dead', 0, -Sidekiq::DeadSet.max_jobs)
      end
    end
  end
end

# Just trying to emulate 
job = {'retry_count' => 4, 'retry' => true}
middleware = SidekiqMiddleware::Stuff.new
middleware.call(worker, job, queue){}
```

[This method](https://github.com/resque/redis-namespace/blob/master/lib/redis/namespace.rb#L311-L317) seems to be the code in question from redis-namespace that triggers it:

```ruby
def multi(&block)
  if block_given?
    namespaced_block(:multi, &block)
  else
    call_with_namespace(:multi)
  end
end
```

Can this be fixed? Or should I just silence it?

**Comment by PatrickTulskie** [comment]
Sorry I'm not super familiar with Sidekiq, but what happens if you change it to:

```
    Sidekiq.redis.multi do |conn|
      conn.zadd('dead', now, payload)
      conn.zremrangebyscore('dead', '-inf', now - Sidekiq::DeadSet.timeout)
      conn.zremrangebyrank('dead', 0, -Sidekiq::DeadSet.max_jobs)
    end
```

**Comment by djberg96** [comment]
@PatrickTulskie Didn't like it, apparently the `.redis` method requires a block, so that raises an error.

**Comment by djberg96** [comment]
@PatrickTulskie However, this does appear to fix it:

```ruby
Sidekiq.redis do |conn|
  conn.multi do |pipeline|
    pipeline.zadd('dead', now, payload)
    pipeline.zremrangebyscore('dead', '-inf', now - Sidekiq::DeadSet.timeout)
    pipeline.zremrangebyrank('dead', 0, -Sidekiq::DeadSet.max_jobs)
  end
end
```

**Comment by djberg96** [comment]
Gonna go ahead and close this since I have a fix. Sorry for the noise, and thanks for the assist @PatrickTulskie.

**Comment by PatrickTulskie** [comment]
Ahh gotcha. That was going to be my next suggestion. Glad you got it fixed @djberg96

**Comment by djberg96** [comment]
Well, upon further review, making that change caused some obscure failures in our middleware stack, but the error message doesn't make it clear what the issue was. FWIW, that `send_to_morgue` code was largely borrowed from their [send_to_morgue](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/job_retry.rb#L251-L263) method which still doesn't use the pipelining.

I guess we'll have to swallow these with `Redis.silence_deprecations`.
