### ISSUE TITLE
uninitialized constant Redis::Client::ALIASES

### ISSUE THREAD

**Issue by ingemar** [resque/redis-namespace#87]
Hello,

I can't find anything related to `ALIASES`, nor does `redis-namespace`.

```
[5] pry(main)> require 'redis/namespace'
NameError: uninitialized constant Redis::Client::ALIASES
from ~/.rvm/gems/ruby-2.1.1@adserver/gems/redis-namespace-0.4.3/lib/redis/namespace.rb:128:in `<class:Namespace>'
```

I'm using redis 3.1.0 and redis-namespace 0.4.3

Any clues?

**Comment by olivierpichon** [comment]
Hey guys,

It looks like this is still not fixed on master, forcing us to fork as @ingemar was mentioning to update redis dependency.

Would it be possible to update that dependency so that this fork is no longer necessary?

Thanks a lot for your help!

**Comment by eftikharEmad** [comment]
Hello,
my rvm list:
`ruby-2.3.0 [ x86_64 ]
 ruby-2.3.1 [ x86_64 ]
 ruby-2.4.1 [ x86_64]`
and I have 
`redis-namespace (1.5.3, 0.4.3)`
rails 
`Rails 5.0.6`
but my project keep raise this error
NameError: uninitialized constant Redis::Client::ALIASES
/Users/eftikharabulibdeh/.rvm/gems/ruby-2.4.1/gems/redis-namespace-0.4.3/lib/redis/namespace.rb:128:in `<class:Namespace>'
does any one have any idea about the reason ?

thank a lot,

**Comment by Morxander** [comment]
@eftikharEmad did you solve it? I'm facing the same issue.

**Comment by yunshang** [comment]
me too
