### ISSUE TITLE
connection_pool 2.1.2

### ISSUE THREAD

**Issue by stephan-roolvink** [resque/redis-namespace#98]
I just upgraded to connection_pool 2.1.2 which adds an explicit disconnect to redis. 

Now redis-namespace is throwing deprecation warnings about blind passthrough. 

Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /opt/rubies/2.1.5/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block in discard!')

I saw in the code that indeed the command disconnect! for redis is missing could someone please fix this?

**Comment by mperham** [comment]
disconnect! is new in redis 3.2.1.  I suspect redis-namespace just needs to add the method to its whitelist.

**Comment by heythisisnate** [comment]
:+1: would like to see these deprecations go away

**Comment by swistaczek** [comment]
:+1:

**Comment by foeken** [comment]
Our logs are being overrun by this warning. Please release a version!

**Comment by mperham** [comment]
@foeken Set REDIS_NAMESPACE_QUIET=1 in the process's environment.

**Comment by foeken** [comment]
Awesome. That's a good fix while we wait for a release! Tnx ;)

**Comment by antonioparisi** [comment]
Thanks @mperham

**Comment by st-keller** [comment]
:+1:

**Comment by foeken** [comment]
I am getting a bit worried by the lack of response from the maintainer...

**Comment by yaauie** [comment]
@foeken if you'd like to throw together a test to validate #99, I'd gladly merge. I haven't had the time.
